### ISSUE TITLE
Why did you delete your Discord account?

### ISSUE THREAD

**Issue by tripulse** [alx365/alx365.github.io#1]
There's a discussion going on r/ProgrammerHumor and also in Trilongue about your leaving. You were just fine and chill but suddenly what you have come onto that you ended up deleting your Discord account? Seriously, this is awkward and everyone is curious.

**Comment by telugu-boy** [comment]
his parents probably found it and he deleted it before they could read anything

**Comment by tripulse** [comment]
why would he hide that to his parents?

**Comment by alx365** [comment]
bruh, i was just trolling
